GET http://localhost:8000/products/ HTTP/1.1

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDI2OTU5LCJpYXQiOjE3NDc0MjY2NTksImp0aSI6IjdmNmVkZjBjOTkwNTRhNmNiZmJkNzQ5NWQ1ZmU2OWE0IiwidXNlcl9pZCI6NH0.IcB1QRh9EuCTkBqOgW2A_48bAJv4Q3gQKY35_hY0lrg

{
    "name": "Smart watch",
    "price": "100",
    "stock": 11,
    "desc": "An amazing new smart watch"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "kunal",
    "password": "123456"
}

###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NjcwODc4LCJpYXQiOjE3NDg2NzA1MjQsImp0aSI6ImZkYWNjOGRmNWExOTQ3NDk4ZjQ5YzgwNjViMzExMjI1IiwidXNlcl9pZCI6NH0.5ATthrvVle3Npg-LJbQMMgo4Yqs4frrZCCV5M432a2M

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0ODc1NjkyNCwiaWF0IjoxNzQ4NjcwNTI0LCJqdGkiOiJhYzg4Y2QzNzQ2MTI0ZTVmOTFiZDU1Nzg0MzUzMDU5NCIsInVzZXJfaWQiOjR9.ZStumF6y7SW7i4ZiwLyH6NO_bGlr1rpJ_RLoGt2yToI"
}