GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/2/ HTTP/1.1

###

DELETE http://localhost:8000/products/2/ HTTP/1.1

###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4Njk1MDA1LCJpYXQiOjE3NDg2OTQ3MDUsImp0aSI6IjBmZWE1MmFjZDhiYTQ4OGM4OTI2ZmQzOTVhNjM1ZTA2IiwidXNlcl9pZCI6Mn0.skBmtHSfSsX1W8drVL5rf8DdZ5z_k3Qw6FpGjuqmTI0

{
    "name": "Smart watch",
    "price": "100",
    "stock": 20,
    "desc": "An amazing new smart watch"
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NzA1NDA1LCJpYXQiOjE3NDg3MDUxMDUsImp0aSI6IjhkYWQxNzVhMjljZTQ4ZTY5MzFhYjg3ZTRlMTc0ZGFiIiwidXNlcl9pZCI6Mn0.rk77EIqvxoZ3iPf1EQtQikk9PWbCuSAHOEwBD_rcFOQ

{
    "name": "Amazing lamp",
    "price": "75.99",
    "stock": 0,
    "desc": "An amazing new lamp"

}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "kunal",
    "password": "Leomessi10@#"
}

###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NjcwODc4LCJpYXQiOjE3NDg2NzA1MjQsImp0aSI6ImZkYWNjOGRmNWExOTQ3NDk4ZjQ5YzgwNjViMzExMjI1IiwidXNlcl9pZCI6NH0.5ATthrvVle3Npg-LJbQMMgo4Yqs4frrZCCV5M432a2M

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0OTQ3ODA4MywiaWF0IjoxNzQ5MzkxNjgzLCJqdGkiOiIyNWEyNzRmM2ZjOTI0YTlmYjc1ODMxM2I1ZmFjMzBjMSIsInVzZXJfaWQiOjZ9.gXMRF1AQipFRU662iRUAZ3BR1nyV1oltA5n7v74pCAM"
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5Mzg3MjY5LCJpYXQiOjE3NDkzODY5NjksImp0aSI6IjljZjMxMzBhZjM2ODQxY2VhOTYxN2E1NWJmZjdlZmYyIiwidXNlcl9pZCI6Nn0.lF7C186Xea0uuNm9XqQur5xnKUCOPK-qd_uOzmzMJ6A

###

POST http://localhost:8000/orders/ HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MzkyNjYyLCJpYXQiOjE3NDkzOTE2ODMsImp0aSI6IjczMWI4MzBkNTViNDQ1M2ZiMDdlNGRlZTU3MGFlMGI3IiwidXNlcl9pZCI6Nn0.HXgd0AY1xbdAYjjI4FpgYfY7B6AGUzwSzAEl2_2hu_w

{
    "status": "Pending",
    "items": [
        {
            "product": 4,
            "quantity": 7
        },
        {
            "product": 5,
            "quantity": 1
        }
    ]
}