GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/2/ HTTP/1.1

###

DELETE http://localhost:8000/products/2/ HTTP/1.1

###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4Njk1MDA1LCJpYXQiOjE3NDg2OTQ3MDUsImp0aSI6IjBmZWE1MmFjZDhiYTQ4OGM4OTI2ZmQzOTVhNjM1ZTA2IiwidXNlcl9pZCI6Mn0.skBmtHSfSsX1W8drVL5rf8DdZ5z_k3Qw6FpGjuqmTI0

{
    "name": "Smart watch",
    "price": "100",
    "stock": 20,
    "desc": "An amazing new smart watch"
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NzA1NDA1LCJpYXQiOjE3NDg3MDUxMDUsImp0aSI6IjhkYWQxNzVhMjljZTQ4ZTY5MzFhYjg3ZTRlMTc0ZGFiIiwidXNlcl9pZCI6Mn0.rk77EIqvxoZ3iPf1EQtQikk9PWbCuSAHOEwBD_rcFOQ

{
    "name": "Amazing lamp",
    "price": "75.99",
    "stock": 0,
    "desc": "An amazing new lamp"

}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5NTcyNjY4LCJpYXQiOjE3NDk1NzE3NjgsImp0aSI6IjRmNjRjMDU1OWIzYzQyY2Y5NTQ1NGY2OTkzNjYyN2UyIiwidXNlcl9pZCI6MX0.4fefAt1TKwvJYm9ovCxQP56T3MGyctiMROI6gGyNTgo

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0OTY1ODA5MywiaWF0IjoxNzQ5NTcxNjkzLCJqdGkiOiJiNjRlMzgyYmFiM2Y0MGJmOTcxZWY0MDdiODg1Yjg1YSIsInVzZXJfaWQiOjZ9.R5PV1sAe-ustDgCkFpEwF3GNhdkTflhlOJbuAmBhL_A"
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5NTcyNjY4LCJpYXQiOjE3NDk1NzE3NjgsImp0aSI6IjRmNjRjMDU1OWIzYzQyY2Y5NTQ1NGY2OTkzNjYyN2UyIiwidXNlcl9pZCI6MX0.4fefAt1TKwvJYm9ovCxQP56T3MGyctiMROI6gGyNTgo

###

POST http://localhost:8000/orders/ HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MzkzODkxLCJpYXQiOjE3NDkzOTE2ODMsImp0aSI6ImM5MDJhODM0MDFmNzQ3YTViY2JmYzEyM2UyOGUxNWZlIiwidXNlcl9pZCI6Nn0.12yulW6bhnVej8CJa8abQ1R_7u1nrrWl4zM8F-K0AXk

{
    "status": "Pending",
    "items": [
        {
            "product": 4,
            "quantity": 7
        },
        {
            "product": 5,
            "quantity": 1
        }
    ]
}

###

PUT http://localhost:8000/orders/b57088e5-feef-4951-91a9-1052c64fcde7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5Mzk1NTM5LCJpYXQiOjE3NDkzOTE2ODMsImp0aSI6ImQxZGMzNDJmOGQxYjQwODNiZmQ4YjkxZTJlNjJlYTZkIiwidXNlcl9pZCI6Nn0.NNZXxKBtwtXBybQEoeaj0Js4CuelE39YoK3IbBSsWAg

{
    "status": "Pending",
    "items": [
        {
            "product": 4,
            "quantity": 3
        },
        {
            "product": 2,
            "quantity": 2
        }
    ]
}

###

DELETE http://localhost:8000/orders/b57088e5-feef-4951-91a9-1052c64fcde7/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5Mzk1NTM5LCJpYXQiOjE3NDkzOTE2ODMsImp0aSI6ImQxZGMzNDJmOGQxYjQwODNiZmQ4YjkxZTJlNjJlYTZkIiwidXNlcl9pZCI6Nn0.NNZXxKBtwtXBybQEoeaj0Js4CuelE39YoK3IbBSsWAg